import 'jquery'
import 'popper.js'
// import 'scrollspy'
import 'bootstrap'
import 'bootstrap/dist/css/bootstrap.css'
import 'magnific-popup'
import 'magnific-popup/dist/magnific-popup.css'
import '../imports/freelancer/css/freelancer.css'
import '../imports/freelancer/js/freelancer'
// import '../imports/css/custom.css'
